# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=q1w2e3r4t5
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.2-nginx
    container_name: app
    volumes:
      - ../carro_backend:/var/www/app
    extra_hosts:
        - "dockerhost:10.0.75.1"
    ports:
      - "80:8080"
    links:
      - mysql
    environment:
      - XDEBUG_ENABLED=true
      - XDEBUG_CONFIG= "remotehost=10.0.75.1"